name: Angular CI/CD with Docker

on:
  workflow_dispatch:
  push:
    branches: [ ] # Changed back to 'master'
  pull_request:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest # Using Ubuntu for better Docker support

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up QEMU (optional for multi-platform builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Stable Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build --prod

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }} # Restored DOCKER_TOKEN

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: viveksinghsahu/learnnn.v1:latest
        platforms: linux/amd64,linux/arm64 # Multi-architecture support
